### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by PiroX4256** [daniLOLZ/ingsw2022-AM45#7]
```
Error:  Failures: 
Error:    FactoryAssistantTest.getAssistant:18 Wrong steps ==> expected: <1> but was: <0>
[INFO] 
Error:  Tests run: 34, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by PiroX4256** [comment]
Tests still failing, please update relative classes in order to make them work.

![image](https://user-images.githubusercontent.com/10998879/162561637-3cc9f68a-99eb-4d96-b9c1-e4244689306b.png)

**Comment by ingconti** [comment]
on Sunday:

[ERROR] Failures: 
[ERROR]   FactoryAssistantTest.correctAssistants:46 Wrong steps with 1card ==> expected: <1> but was: <0>
[ERROR]   FactoryAssistantTest.getAssistant:19 Wrong steps ==> expected: <4> but was: <0>
[INFO] 
[ERROR] Tests run: 37, Failures: 2, Errors: 0, Skipped: 0

**Comment by cerutigiacomo** [comment]
Still.
