### ISSUE TITLE
avoid magic numbers

### ISSUE THREAD

**Issue by ingconti** [daniLOLZ/ingsw2022-AM45#9]
if(idWizard !=0 && idWizard != 10 && idWizard != 20 && idWizard != 30)
            idWizard = 0;

        List<Assistant> assistants = new ArrayList<>();

        for(int cards = 1; cards <= 10; cards++){

pls use a final static..... for your "10"

**Comment by Zeekuri** [comment]
![image](https://user-images.githubusercontent.com/72214755/167113681-779c61bd-044e-46f6-822e-752f2504e2ee.png)
We removed every magic number sitting in FactoryWizard. We'll avoid magic numbers without a proper //TODO in the future
